package com.mobdeve.s13.group1.budgetbuilder

enum class Keys {
    KEY_FURNITURE_NAME,
    KEY_FURNITURE_PRICE,
    KEY_FURNITURE_IMG,
    KEY_FURNITURE_ID,
    KEY_FURNITURE_TYPE,
    KEY_FURNITURE_PATH,
    KEY_BALANCE,
    KEY_EXPENSES,
    KEY_ROOM_ID,

    KEY_COLUMN_NAME,
    KEY_AGG_TYPE,
    KEY_COLUMN_ALIAS,

    KEY_VIEW_EXPENSE_TYPE,
    KEY_VIEW_EXPENSE_AMOUNT,
    KEY_VIEW_EXPENSE_DESC,
    KEY_VIEW_EXPENSE_DATE,
    KEY_VIEW_EXPENSE_ID,

    KEY_EDIT_EXPENSE_TYPE,
    KEY_EDIT_EXPENSE_AMOUNT,
    KEY_EDIT_EXPENSE_DESC,
    KEY_EDIT_EXPENSE_ID,
    KEY_EDIT_EXPENSE_DATE,

    KEY_BUDGET,
    KEY_CURRENCY,
    KEY_PREV_DATE,
    KEY_BUDGET_ID,
    KEY_DEFAULT_BUDGET,

    KEY_DIALOG_CANCEL,

    KEY_EARNED_COINS,
    KEY_MONTH,
    KEY_YEAR
}