package com.mobdeve.s13.group1.budgetbuilder

enum class Keys {
    KEY_FURNITURE_NAME,
    KEY_FURNITURE_PRICE,
    KEY_FURNITURE_IMG,
    KEY_FURNITURE_ID,
    KEY_FURNITURE_TYPE,
    KEY_BALANCE,
    KEY_DEFAULT_BALANCE,

    KEY_COLUMN_NAME,
    KEY_AGG_TYPE,
    KEY_COLUMN_ALIAS
}